import { Resort } from "@/types";

export const resorts: Resort[] = [
  {
    id: "resort1",
    name: "شاليه فخم VIP",
    type: "vip",
    description:
      "شاليه فاخر مع مسبح خاص وشاطئ خاص للاستمتاع بإقامة مميزة",
    bedrooms: 4,
    bathrooms: 5,
    priceRegular: 150,
    priceWeekend: 200,
    currency: "د.ب",
    features: [
      "4 غرف نوم واسعة ومجهزة بالكامل",
      "5 دورات مياه",
      "صالة كبيرة للجلوس والاسترخاء",
      "مطبخ مجهز بالكامل مع مكان مخصص لتناول الطعام",
      "جلسة خارجية مريحة بالقرب من المسبح",
    ],
    amenities: [
      "مسبح خارجي خاص متاح للاستخدام في أي وقت",
      "منطقة شواء (BBQ) مجهزة بالكامل",
      "جلسات خارجية مطلة على البحر",
      "موقف سيارات خاص",
      "واي فاي مجاني عالي السرعة",
      "تكييف مركزي في جميع الغرف",
      "شاطئ خاص مع إمكانية الوصول المباشر",
      "مكينة آيسكريم",
      "مكينة ثلج (تنتج الثلج كل 10 دقائق)",
      "مكينة قهوة",
    ],
    images: [
      "/assets/resort1/1.jpeg",
      "/assets/resort1/1.png",
      "/assets/resort1/2.jpeg",
      "/assets/resort1/3.jpeg",
      "/assets/resort1/4.jpeg",
      "/assets/resort1/5.jpeg",
      "/assets/resort1/6.jpeg",
      "/assets/resort1/7.jpeg",
      "/assets/resort1/8.jpeg",
      "/assets/resort1/9.jpeg",
      "/assets/resort1/10.jpeg",
      "/assets/resort1/11.jpeg",
      "/assets/resort1/12.jpeg",
      "/assets/resort1/13.jpeg",
      "/assets/resort1/14.jpeg",
      "/assets/resort1/15.jpeg",
      "/assets/resort1/16.jpeg",
      "/assets/resort1/17.jpeg",
      "/assets/resort1/18.jpeg",
      "/assets/resort1/19.jpeg",
      "/assets/resort1/20.jpeg",
      "/assets/resort1/21.jpeg",
      "/assets/resort1/22.jpeg",
      "/assets/resort1/hero.jpeg",
      "/assets/resort1/hero.png",
      "/assets/resort1/hero2.jpeg",
      "/assets/resort1/hero3.jpeg",
      "/assets/resort1/hero3.png",
      "/assets/resort1/hero4.jpeg",
      "/assets/resort1/hero4.png",
    ],
    video: "/assets/resort1/full-resort-vedio.mp4",
    hasPrivatePool: true,
    hasPrivateBeach: true,
    beachAccess: "direct",

    paymentLink: "https://buy.stripe.com/test_8x2aEX7R6fFa3Oi9s36AM00",
    deposit: 50,
    checkIn: "3:00 عصرًا",
    checkOut: "12:00 ظهرًا",
    policy: [
      "يرجى الالتزام بموعد الدخول 3:00 عصرًا.",
      "يرجى الالتزام بموعد الخروج 12:00 ظهرًا في اليوم التالي.",
      "يرجى التأكد من التواريخ قبل إتمام الحجز، علمًا بأن التواريخ غير قابلة للتغيير أو التعديل بعد تأكيد الحجز.",
      "المبلغ المدفوع لتأكيد الحجز غير مسترجع في حال الإلغاء أو عدم الحضور لأي سبب كان.",
      "يتم استيفاء مبلغ تأمين (ضمان) قدره 50 دينار، ويُعاد عند المغادرة بعد التأكد من سلامة الشاليه ومحتوياته.",
      "في حال حدوث كسر أو تخريب في الشاليه أو مرافقه، وإذا كانت قيمة الأضرار تتجاوز مبلغ التأمين، يلتزم المستأجر بدفع كامل التكاليف الإضافية.",
      "يُمنع الإزعاج أو التسبب بأي تصرف يخل بالهدوء العام.",
      "يُمنع تشغيل الموسيقى بصوت مرتفع داخل الشاليه أو في المناطق الخارجية.",
      "يحق للإدارة اتخاذ الإجراء المناسب في حال مخالفة أي من القوانين المذكورة أعلاه.",
    ],
    location: {
      lat: 26.290121,
      lng: 50.669178,
      villa: "1625",
      road: "5714",
      block: "257",
      area: "Amwaj",
    },
  },
  {
    id: "resort2",
    name: "شاليه 4 غرف نوم ماستر",
    type: "standard",
    description: "شاليه عائلي مريح مع مسبح خاص وإطلالة على البحر",
    bedrooms: 4,
    bathrooms: 4,
    priceRegular: 100,
    priceWeekend: 130,
    currency: "د.ب",
    features: [
      "4 غرف نوم ماستر",
      "صالة واسعة",
      "مطبخ أمريكي مفتوح",
      "جلسة خارجية عند المسبح",
    ],
    amenities: [
      "مسبح خاص",
      "درج لنزول البحر",
      "عدة شواء",
      "واي فاي مجاني",
      "تكييف مركزي",
      "موقف سيارات",
    ],
    images: [
      "/assets/resort2/1.jpeg",
      "/assets/resort2/2.jpeg",
      "/assets/resort2/3.jpeg",
      "/assets/resort2/4.jpeg",
      "/assets/resort2/5.jpeg",
      "/assets/resort2/6.jpeg",
      "/assets/resort2/7.jpeg",
      "/assets/resort2/8.jpeg",
      "/assets/resort2/9.jpeg",
      "/assets/resort2/10.jpeg",
      "/assets/resort2/11.jpeg",
      "/assets/resort2/12.jpeg",
      "/assets/resort2/13.jpeg",
      "/assets/resort2/14.jpeg",
      "/assets/resort2/15.jpeg",
    ],
    hasPrivatePool: true,
    hasPrivateBeach: false,
    beachAccess: "stairs",
    paymentLink: "https://buy.stripe.com/test_8x2aEX7R6fFa3Oi9s36AM00",
    deposit: 50,
    checkIn: "3:00 عصرًا",
    checkOut: "12:00 ظهرًا",
    policy: [
      "يرجى الالتزام بموعد الدخول 3:00 عصرًا.",
      "يرجى الالتزام بموعد الخروج 12:00 ظهرًا في اليوم التالي.",
      "يرجى التأكد من التواريخ قبل إتمام الحجز، علمًا بأن التواريخ غير قابلة للتغيير أو التعديل بعد تأكيد الحجز.",
      "المبلغ المدفوع لتأكيد الحجز غير مسترجع في حال الإلغاء أو عدم الحضور لأي سبب كان.",
      "يتم استيفاء مبلغ تأمين (ضمان) قدره 50 دينار، ويُعاد عند المغادرة بعد التأكد من سلامة الشاليه ومحتوياته.",
      "في حال حدوث كسر أو تخريب في الشاليه أو مرافقه، وإذا كانت قيمة الأضرار تتجاوز مبلغ التأمين، يلتزم المستأجر بدفع كامل التكاليف الإضافية.",
      "يُمنع الإزعاج أو التسبب بأي تصرف يخل بالهدوء العام.",
      "يُمنع تشغيل الموسيقى بصوت مرتفع داخل الشاليه أو في المناطق الخارجية.",
      "يحق للإدارة اتخاذ الإجراء المناسب في حال مخالفة أي من القوانين المذكورة أعلاه.",
    ],
    location: {
      lat: 26.290121,
      lng: 50.669178,
      villa: "1626",
      road: "5715",
      block: "258",
      area: "Amwaj",
    },
  },
];

export const getResortById = (id: string): Resort | undefined =>
  resorts.find((r) => r.id === id);

export const getResortByIdOrThrow = (id: string): Resort => {
  const resort = resorts.find((r) => r.id === id);
  if (!resort) {
    throw new Error(`Resort with id ${id} not found`);
  }
  return resort;
};
